# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-09 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('Unpublished', 'unpublished'), ('Published', 'published')], default='Unpublished', max_length=11),
        ),
    ]
