# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20170313_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
