# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 04:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20170313_1602'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'stories'},
        ),
        migrations.AddField(
            model_name='story',
            name='story',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
