# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 04:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20170315_1704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='story',
            new_name='text',
        ),
    ]
