# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20170315_1704'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_text', tinymce.models.HTMLField(blank=True)),
                ('submission_guidelines', tinymce.models.HTMLField(blank=True)),
            ],
        ),
    ]
