# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 04:40
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_site'),
    ]

    operations = [
        migrations.CreateModel(
            name='About_Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission_Guidelines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_guidelines', tinymce.models.HTMLField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Site',
        ),
    ]
