# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 04:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20170316_1740'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about_text',
            options={'verbose_name_plural': 'About_Text'},
        ),
        migrations.AlterModelOptions(
            name='submission_guidelines',
            options={'verbose_name_plural': 'Submission_Guidelines'},
        ),
    ]
