# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 09:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20170316_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission_guidelines',
            old_name='submission_guidelines',
            new_name='text',
        ),
    ]
